name: build-satellite

on:
  workflow_dispatch:
    inputs:
      companion-host:
        type: string
        description: Companion IP/Hostname
        default: '192.168.0.5'
        required: true
      companion-port:
        type: string
        description: Companion Port
        default: '16622'
        required: true
      armbian-board:
        type: choice
        description: Armbian Board
        options: 
        - 'orangepizero2'
        default: 'orangepizero2'

env:
  BUILD_MINIMAL: yes
  KERNEL_ONLY: no
  KERNEL_CONFIGURE: no
  BOARD: orangepilite
  BRANCH: current
  RELEASE: jammy
  BUILD_DESKTOP: no
  COMPRESS_OUTPUTIMAGE: sha,img

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download source code
        run: |
          git clone --depth=1 --branch=main https://github.com/armbian/build
          
      - name: Cache armbian build cache
        uses: actions/cache@v3
        with:
          path: ./build/cache
          key: armbian
          
      - name: Build Armbian
        id: build
        run: |
          cd build
          ./compile.sh BUILD_MINIMAL=$BUILD_MINIMAL KERNEL_ONLY=$KERNEL_ONLY KERNEL_CONFIGURE=$KERNEL_CONFIGURE BOARD=$BOARD BRANCH=$BRANCH RELEASE=$RELEASE BUILD_DESKTOP=$BUILD_DESKTOP COMPRESS_OUTPUTIMAGE=$COMPRESS_OUTPUTIMAGE
          echo "status::success" >> $GITHUB_OUTPUT
          
      - name: Upload Armbian image
        uses: actions/upload-artifact@master
        if: steps.build.outputs.status == 'success'
        with:
          name: Armbian_firmware
          path: output/images/*
