name: Build matrix

on:
  workflow_dispatch

jobs:
  pi-img:
    strategy:
      matrix:
        url: [https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.05.3_Orangepizero2_jammy_current_5.15.48.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.05.3_Orangepizero2_jammy_edge_5.17.11.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.08.1_Orangepizero2_jammy_current_5.15.63.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.08.2_Orangepizero2_jammy_current_5.15.69.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.08.7_Orangepizero2_jammy_edge_5.19.16.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.08.7_Orangepizero2_jammy_edge_5.19.16_minimal.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.11.1_Orangepizero2_jammy_edge_6.0.10.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.11.1_Orangepizero2_jammy_edge_6.0.10_minimal.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.11.3_Orangepizero2_jammy_edge_6.1.4.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.11.3_Orangepizero2_jammy_edge_6.1.4_minimal.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_22.11.3_Orangepizero2_jammy_legacy_4.9.318.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_23.02.2_Orangepizero2_jammy_edge_6.1.11.img.xz, https://armbian.tnahosting.net/archive/orangepizero2/archive/Armbian_23.02.2_Orangepizero2_jammy_edge_6.1.11_minimal.img.xz]
    runs-on: ubuntu-latest
    name: build image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: install packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      - name: build image
        run: |
          sudo packer init companion-satellite.pkr.hcl
          sudo packer build -var "url=${{ matrix.url }}" companion-satellite.pkr.hcl
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: compress image
        shell: bash
        run: |
          cd output-satellitepi

          sudo apt-get install -y zerofree
          device="$(sudo losetup --partscan --show --find armbian-companion-satellite.img)"
          sudo zerofree "${device}p1"
          sudo losetup --detach "$device"

          sudo gzip -n armbian-companion-satellite.img
          DATE=$(date +"%Y-%m-%d")
          targetname=armbian-companion-satellite-${DATE}-${{ github.run_id }}.img.gz
          sudo mv armbian-companion-satellite.img.gz ${targetname}

      - name: Upload Armbian image
        uses: actions/upload-artifact@v3
        with:
          name: Armbian_firmware
          path: output-satellitepi/*
